// Generated by scripts/discover_fdc_nutrients.mjs.
// Sampled 2366 unique foods on 2026-06-13T16:23:41.195Z.
// This catalog is consumed by src/variables/allNutrients.ts.

export const DISCOVERED_FDC_NUTRIENTS = [
	{
		"id": 1003,
		"label": "Protein",
		"unit": "g"
	},
	{
		"id": 1004,
		"label": "Total lipid (fat)",
		"unit": "g"
	},
	{
		"id": 1093,
		"label": "Sodium, Na",
		"unit": "mg"
	},
	{
		"id": 1005,
		"label": "Carbohydrate, by difference",
		"unit": "g"
	},
	{
		"id": 1008,
		"label": "Energy",
		"unit": "kcal"
	},
	{
		"id": 1087,
		"label": "Calcium, Ca",
		"unit": "mg"
	},
	{
		"id": 1089,
		"label": "Iron, Fe",
		"unit": "mg"
	},
	{
		"id": 1258,
		"label": "Fatty acids, total saturated",
		"unit": "g"
	},
	{
		"id": 1253,
		"label": "Cholesterol",
		"unit": "mg"
	},
	{
		"id": 1079,
		"label": "Fiber, total dietary",
		"unit": "g"
	},
	{
		"id": 1092,
		"label": "Potassium, K",
		"unit": "mg"
	},
	{
		"id": 1162,
		"label": "Vitamin C, total ascorbic acid",
		"unit": "mg"
	},
	{
		"id": 1104,
		"label": "Vitamin A, IU",
		"unit": "IU"
	},
	{
		"id": 1051,
		"label": "Water",
		"unit": "g"
	},
	{
		"id": 1007,
		"label": "Ash",
		"unit": "g"
	},
	{
		"id": 1091,
		"label": "Phosphorus, P",
		"unit": "mg"
	},
	{
		"id": 1095,
		"label": "Zinc, Zn",
		"unit": "mg"
	},
	{
		"id": 2000,
		"label": "Total Sugars",
		"unit": "g"
	},
	{
		"id": 1090,
		"label": "Magnesium, Mg",
		"unit": "mg"
	},
	{
		"id": 1167,
		"label": "Niacin",
		"unit": "mg"
	},
	{
		"id": 1165,
		"label": "Thiamin",
		"unit": "mg"
	},
	{
		"id": 1175,
		"label": "Vitamin B-6",
		"unit": "mg"
	},
	{
		"id": 1166,
		"label": "Riboflavin",
		"unit": "mg"
	},
	{
		"id": 1098,
		"label": "Copper, Cu",
		"unit": "mg"
	},
	{
		"id": 1062,
		"label": "Energy",
		"unit": "kJ"
	},
	{
		"id": 1292,
		"label": "Fatty acids, total monounsaturated",
		"unit": "g"
	},
	{
		"id": 1293,
		"label": "Fatty acids, total polyunsaturated",
		"unit": "g"
	},
	{
		"id": 1178,
		"label": "Vitamin B-12",
		"unit": "µg"
	},
	{
		"id": 1177,
		"label": "Folate, total",
		"unit": "µg"
	},
	{
		"id": 1106,
		"label": "Vitamin A, RAE",
		"unit": "µg"
	},
	{
		"id": 1265,
		"label": "SFA 16:0",
		"unit": "g"
	},
	{
		"id": 1266,
		"label": "SFA 18:0",
		"unit": "g"
	},
	{
		"id": 1105,
		"label": "Retinol",
		"unit": "µg"
	},
	{
		"id": 1269,
		"label": "PUFA 18:2",
		"unit": "g"
	},
	{
		"id": 1187,
		"label": "Folate, food",
		"unit": "µg"
	},
	{
		"id": 1268,
		"label": "MUFA 18:1",
		"unit": "g"
	},
	{
		"id": 1186,
		"label": "Folic acid",
		"unit": "µg"
	},
	{
		"id": 1103,
		"label": "Selenium, Se",
		"unit": "µg"
	},
	{
		"id": 1264,
		"label": "SFA 14:0",
		"unit": "g"
	},
	{
		"id": 1270,
		"label": "PUFA 18:3",
		"unit": "g"
	},
	{
		"id": 1190,
		"label": "Folate, DFE",
		"unit": "µg"
	},
	{
		"id": 1275,
		"label": "MUFA 16:1",
		"unit": "g"
	},
	{
		"id": 1101,
		"label": "Manganese, Mn",
		"unit": "mg"
	},
	{
		"id": 1110,
		"label": "Vitamin D (D2 + D3), International Units",
		"unit": "IU"
	},
	{
		"id": 1277,
		"label": "MUFA 20:1",
		"unit": "g"
	},
	{
		"id": 1170,
		"label": "Pantothenic acid",
		"unit": "mg"
	},
	{
		"id": 1263,
		"label": "SFA 12:0",
		"unit": "g"
	},
	{
		"id": 1271,
		"label": "PUFA 20:4",
		"unit": "g"
	},
	{
		"id": 1262,
		"label": "SFA 10:0",
		"unit": "g"
	},
	{
		"id": 1278,
		"label": "PUFA 20:5 n-3 (EPA)",
		"unit": "g"
	},
	{
		"id": 1272,
		"label": "PUFA 22:6 n-3 (DHA)",
		"unit": "g"
	},
	{
		"id": 1261,
		"label": "SFA 8:0",
		"unit": "g"
	},
	{
		"id": 1114,
		"label": "Vitamin D (D2 + D3)",
		"unit": "µg"
	},
	{
		"id": 1280,
		"label": "PUFA 22:5 n-3 (DPA)",
		"unit": "g"
	},
	{
		"id": 1279,
		"label": "MUFA 22:1",
		"unit": "g"
	},
	{
		"id": 1276,
		"label": "PUFA 18:4",
		"unit": "g"
	},
	{
		"id": 1260,
		"label": "SFA 6:0",
		"unit": "g"
	},
	{
		"id": 1259,
		"label": "SFA 4:0",
		"unit": "g"
	},
	{
		"id": 1257,
		"label": "Fatty acids, total trans",
		"unit": "g"
	},
	{
		"id": 1109,
		"label": "Vitamin E (alpha-tocopherol)",
		"unit": "mg"
	},
	{
		"id": 1107,
		"label": "Carotene, beta",
		"unit": "µg"
	},
	{
		"id": 1018,
		"label": "Alcohol, ethyl",
		"unit": "g"
	},
	{
		"id": 1108,
		"label": "Carotene, alpha",
		"unit": "µg"
	},
	{
		"id": 1185,
		"label": "Vitamin K (phylloquinone)",
		"unit": "µg"
	},
	{
		"id": 1120,
		"label": "Cryptoxanthin, beta",
		"unit": "µg"
	},
	{
		"id": 1122,
		"label": "Lycopene",
		"unit": "µg"
	},
	{
		"id": 1123,
		"label": "Lutein + zeaxanthin",
		"unit": "µg"
	},
	{
		"id": 1057,
		"label": "Caffeine",
		"unit": "mg"
	},
	{
		"id": 1058,
		"label": "Theobromine",
		"unit": "mg"
	},
	{
		"id": 1180,
		"label": "Choline, total",
		"unit": "mg"
	},
	{
		"id": 1246,
		"label": "Vitamin B-12, added",
		"unit": "µg"
	},
	{
		"id": 1242,
		"label": "Vitamin E, added",
		"unit": "mg"
	},
	{
		"id": 1212,
		"label": "Isoleucine",
		"unit": "g"
	},
	{
		"id": 1213,
		"label": "Leucine",
		"unit": "g"
	},
	{
		"id": 1214,
		"label": "Lysine",
		"unit": "g"
	},
	{
		"id": 1219,
		"label": "Valine",
		"unit": "g"
	},
	{
		"id": 1211,
		"label": "Threonine",
		"unit": "g"
	},
	{
		"id": 1221,
		"label": "Histidine",
		"unit": "g"
	},
	{
		"id": 1215,
		"label": "Methionine",
		"unit": "g"
	},
	{
		"id": 1217,
		"label": "Phenylalanine",
		"unit": "g"
	},
	{
		"id": 1220,
		"label": "Arginine",
		"unit": "g"
	},
	{
		"id": 1218,
		"label": "Tyrosine",
		"unit": "g"
	},
	{
		"id": 1222,
		"label": "Alanine",
		"unit": "g"
	},
	{
		"id": 1224,
		"label": "Glutamic acid",
		"unit": "g"
	},
	{
		"id": 1225,
		"label": "Glycine",
		"unit": "g"
	},
	{
		"id": 1227,
		"label": "Serine",
		"unit": "g"
	},
	{
		"id": 1223,
		"label": "Aspartic acid",
		"unit": "g"
	},
	{
		"id": 1226,
		"label": "Proline",
		"unit": "g"
	},
	{
		"id": 1210,
		"label": "Tryptophan",
		"unit": "g"
	},
	{
		"id": 1216,
		"label": "Cystine",
		"unit": "g"
	},
	{
		"id": 1012,
		"label": "Fructose",
		"unit": "g"
	},
	{
		"id": 1011,
		"label": "Glucose",
		"unit": "g"
	},
	{
		"id": 1014,
		"label": "Maltose",
		"unit": "g"
	},
	{
		"id": 1013,
		"label": "Lactose",
		"unit": "g"
	},
	{
		"id": 1010,
		"label": "Sucrose",
		"unit": "g"
	},
	{
		"id": 1267,
		"label": "SFA 20:0",
		"unit": "g"
	},
	{
		"id": 1273,
		"label": "SFA 22:0",
		"unit": "g"
	},
	{
		"id": 1300,
		"label": "SFA 17:0",
		"unit": "g"
	},
	{
		"id": 1299,
		"label": "SFA 15:0",
		"unit": "g"
	},
	{
		"id": 1274,
		"label": "MUFA 14:1",
		"unit": "g"
	},
	{
		"id": 1301,
		"label": "SFA 24:0",
		"unit": "g"
	},
	{
		"id": 1075,
		"label": "Galactose",
		"unit": "g"
	},
	{
		"id": 1313,
		"label": "PUFA 20:2 n-6 c,c",
		"unit": "g"
	},
	{
		"id": 1323,
		"label": "MUFA 17:1",
		"unit": "g"
	},
	{
		"id": 1333,
		"label": "MUFA 15:1",
		"unit": "g"
	},
	{
		"id": 1325,
		"label": "PUFA 20:3",
		"unit": "g"
	},
	{
		"id": 1126,
		"label": "Tocopherol, gamma",
		"unit": "mg"
	},
	{
		"id": 1125,
		"label": "Tocopherol, beta",
		"unit": "mg"
	},
	{
		"id": 1127,
		"label": "Tocopherol, delta",
		"unit": "mg"
	},
	{
		"id": 1312,
		"label": "MUFA 24:1 c",
		"unit": "g"
	},
	{
		"id": 1129,
		"label": "Tocotrienol, beta",
		"unit": "mg"
	},
	{
		"id": 1130,
		"label": "Tocotrienol, gamma",
		"unit": "mg"
	},
	{
		"id": 1131,
		"label": "Tocotrienol, delta",
		"unit": "mg"
	},
	{
		"id": 1128,
		"label": "Tocotrienol, alpha",
		"unit": "mg"
	},
	{
		"id": 1009,
		"label": "Starch",
		"unit": "g"
	},
	{
		"id": 1404,
		"label": "PUFA 18:3 n-3 c,c,c (ALA)",
		"unit": "g"
	},
	{
		"id": 1321,
		"label": "PUFA 18:3 n-6 c,c,c",
		"unit": "g"
	},
	{
		"id": 1315,
		"label": "MUFA 18:1 c",
		"unit": "g"
	},
	{
		"id": 1304,
		"label": "TFA 18:1 t",
		"unit": "g"
	},
	{
		"id": 1198,
		"label": "Betaine",
		"unit": "mg"
	},
	{
		"id": 1184,
		"label": "Vitamin K (Dihydrophylloquinone)",
		"unit": "µg"
	},
	{
		"id": 1411,
		"label": "PUFA 22:4",
		"unit": "g"
	},
	{
		"id": 1316,
		"label": "PUFA 18:2 n-6 c,c",
		"unit": "g"
	},
	{
		"id": 1329,
		"label": "Fatty acids, total trans-monoenoic",
		"unit": "g"
	},
	{
		"id": 1112,
		"label": "Vitamin D3 (cholecalciferol)",
		"unit": "µg"
	},
	{
		"id": 1314,
		"label": "MUFA 16:1 c",
		"unit": "g"
	},
	{
		"id": 1331,
		"label": "Fatty acids, total trans-polyenoic",
		"unit": "g"
	},
	{
		"id": 1406,
		"label": "PUFA 20:3 n-6",
		"unit": "g"
	},
	{
		"id": 1303,
		"label": "TFA 16:1 t",
		"unit": "g"
	},
	{
		"id": 1311,
		"label": "PUFA 18:2 CLAs",
		"unit": "g"
	},
	{
		"id": 1317,
		"label": "MUFA 22:1 c",
		"unit": "g"
	},
	{
		"id": 1405,
		"label": "PUFA 20:3 n-3",
		"unit": "g"
	},
	{
		"id": 1306,
		"label": "TFA 18:2 t not further defined",
		"unit": "g"
	},
	{
		"id": 1305,
		"label": "TFA 22:1 t",
		"unit": "g"
	},
	{
		"id": 1283,
		"label": "Phytosterols",
		"unit": "mg"
	},
	{
		"id": 1235,
		"label": "Sugars, added",
		"unit": "g"
	},
	{
		"id": 1099,
		"label": "Fluoride, F",
		"unit": "µg"
	},
	{
		"id": 1183,
		"label": "Vitamin K (Menaquinone-4)",
		"unit": "µg"
	},
	{
		"id": 1409,
		"label": "PUFA 18:3i",
		"unit": "g"
	},
	{
		"id": 1002,
		"label": "Nitrogen",
		"unit": "g"
	},
	{
		"id": 1228,
		"label": "Hydroxyproline",
		"unit": "g"
	},
	{
		"id": 1332,
		"label": "SFA 13:0",
		"unit": "g"
	},
	{
		"id": 2047,
		"label": "Energy (Atwater General Factors)",
		"unit": "kcal"
	},
	{
		"id": 2048,
		"label": "Energy (Atwater Specific Factors)",
		"unit": "kcal"
	},
	{
		"id": 1285,
		"label": "Stigmasterol",
		"unit": "mg"
	},
	{
		"id": 1288,
		"label": "Beta-sitosterol",
		"unit": "mg"
	},
	{
		"id": 1286,
		"label": "Campesterol",
		"unit": "mg"
	},
	{
		"id": 1111,
		"label": "Vitamin D2 (ergocalciferol)",
		"unit": "µg"
	},
	{
		"id": 1176,
		"label": "Biotin",
		"unit": "µg"
	},
	{
		"id": 1063,
		"label": "Sugars, Total",
		"unit": "g"
	},
	{
		"id": 1410,
		"label": "PUFA 21:5",
		"unit": "g"
	},
	{
		"id": 1102,
		"label": "Molybdenum, Mo",
		"unit": "µg"
	},
	{
		"id": 2016,
		"label": "PUFA 18:2 c",
		"unit": "g"
	},
	{
		"id": 2018,
		"label": "PUFA 18:3 c",
		"unit": "g"
	},
	{
		"id": 2026,
		"label": "PUFA 20:2 c",
		"unit": "g"
	},
	{
		"id": 1334,
		"label": "PUFA 22:2",
		"unit": "g"
	},
	{
		"id": 1335,
		"label": "SFA 11:0",
		"unit": "g"
	},
	{
		"id": 2023,
		"label": "PUFA 20:5c",
		"unit": "g"
	},
	{
		"id": 2024,
		"label": "PUFA 22:5 c",
		"unit": "g"
	},
	{
		"id": 2025,
		"label": "PUFA 22:6 c",
		"unit": "g"
	},
	{
		"id": 2020,
		"label": "PUFA 20:3 c",
		"unit": "g"
	},
	{
		"id": 1414,
		"label": "PUFA 20:3 n-9",
		"unit": "g"
	},
	{
		"id": 1100,
		"label": "Iodine, I",
		"unit": "µg"
	},
	{
		"id": 1085,
		"label": "Total fat (NLEA)",
		"unit": "g"
	},
	{
		"id": 2012,
		"label": "MUFA 20:1 c",
		"unit": "g"
	},
	{
		"id": 2014,
		"label": "MUFA 22:1 n-9",
		"unit": "g"
	},
	{
		"id": 2022,
		"label": "PUFA 20:4c",
		"unit": "g"
	},
	{
		"id": 2019,
		"label": "TFA 18:3 t",
		"unit": "g"
	},
	{
		"id": 2009,
		"label": "MUFA 14:1 c",
		"unit": "g"
	},
	{
		"id": 2010,
		"label": "MUFA 17:1 c",
		"unit": "g"
	},
	{
		"id": 2006,
		"label": "SFA 21:0",
		"unit": "g"
	},
	{
		"id": 2066,
		"label": "Vitamin A",
		"unit": "mg"
	},
	{
		"id": 1310,
		"label": "TFA 18:2 t,t",
		"unit": "g"
	},
	{
		"id": 2008,
		"label": "MUFA 12:1",
		"unit": "g"
	},
	{
		"id": 2015,
		"label": "MUFA 22:1 n-11",
		"unit": "g"
	},
	{
		"id": 2021,
		"label": "PUFA 22:3",
		"unit": "g"
	},
	{
		"id": 2007,
		"label": "SFA 23:0",
		"unit": "g"
	},
	{
		"id": 2003,
		"label": "SFA 5:0",
		"unit": "g"
	},
	{
		"id": 2004,
		"label": "SFA 7:0",
		"unit": "g"
	},
	{
		"id": 2005,
		"label": "SFA 9:0",
		"unit": "g"
	},
	{
		"id": 1281,
		"label": "TFA 14:1 t",
		"unit": "g"
	},
	{
		"id": 2013,
		"label": "TFA 20:1 t",
		"unit": "g"
	},
	{
		"id": 1137,
		"label": "Boron, B",
		"unit": "µg"
	},
	{
		"id": 1097,
		"label": "Cobalt, Co",
		"unit": "µg"
	},
	{
		"id": 1330,
		"label": "Fatty acids, total trans-dienoic",
		"unit": "g"
	},
	{
		"id": 1146,
		"label": "Nickel, Ni",
		"unit": "µg"
	},
	{
		"id": 1094,
		"label": "Sulfur, S",
		"unit": "mg"
	},
	{
		"id": 2017,
		"label": "TFA 18:2 t",
		"unit": "g"
	},
	{
		"id": 1232,
		"label": "Cysteine",
		"unit": "g"
	},
	{
		"id": 1307,
		"label": "PUFA 18:2 i",
		"unit": "g"
	},
	{
		"id": 1072,
		"label": "Carbohydrate, other",
		"unit": "g"
	},
	{
		"id": 1294,
		"label": "Beta-sitostanol",
		"unit": "mg"
	},
	{
		"id": 1287,
		"label": "Brassicasterol",
		"unit": "mg"
	},
	{
		"id": 1289,
		"label": "Campestanol",
		"unit": "mg"
	},
	{
		"id": 1296,
		"label": "Delta-5-avenasterol",
		"unit": "mg"
	},
	{
		"id": 1113,
		"label": "25-hydroxycholecalciferol",
		"unit": "µg"
	},
	{
		"id": 1050,
		"label": "Carbohydrate, by summation",
		"unit": "g"
	},
	{
		"id": 1194,
		"label": "Choline, free",
		"unit": "mg"
	},
	{
		"id": 1197,
		"label": "Choline, from glycerophosphocholine",
		"unit": "mg"
	},
	{
		"id": 1195,
		"label": "Choline, from phosphocholine",
		"unit": "mg"
	},
	{
		"id": 1196,
		"label": "Choline, from phosphotidyl choline",
		"unit": "mg"
	},
	{
		"id": 1199,
		"label": "Choline, from sphingomyelin",
		"unit": "mg"
	},
	{
		"id": 1082,
		"label": "Fiber, soluble",
		"unit": "g"
	},
	{
		"id": 2038,
		"label": "High Molecular Weight Dietary Fiber (HMWDF)",
		"unit": "g"
	},
	{
		"id": 2065,
		"label": "Low Molecular Weight Dietary Fiber (LMWDF)",
		"unit": "g"
	},
	{
		"id": 2033,
		"label": "Total dietary fiber (AOAC 2011.25)",
		"unit": "g"
	},
	{
		"id": 2058,
		"label": "Beta-glucan",
		"unit": "g"
	},
	{
		"id": 1084,
		"label": "Fiber, insoluble",
		"unit": "g"
	},
	{
		"id": 1408,
		"label": "PUFA 20:4 n-6",
		"unit": "g"
	},
	{
		"id": 2052,
		"label": "Delta-7-Stigmastenol",
		"unit": "mg"
	},
	{
		"id": 1298,
		"label": "Phytosterols, other",
		"unit": "mg"
	},
	{
		"id": 2053,
		"label": "Stigmastadiene",
		"unit": "mg"
	},
	{
		"id": 1161,
		"label": "cis-Lutein/Zeaxanthin",
		"unit": "µg"
	},
	{
		"id": 1121,
		"label": "Lutein",
		"unit": "µg"
	},
	{
		"id": 1119,
		"label": "Zeaxanthin",
		"unit": "µg"
	},
	{
		"id": 1159,
		"label": "cis-beta-Carotene",
		"unit": "µg"
	},
	{
		"id": 1160,
		"label": "cis-Lycopene",
		"unit": "µg"
	},
	{
		"id": 2032,
		"label": "Cryptoxanthin, alpha",
		"unit": "µg"
	},
	{
		"id": 1071,
		"label": "Resistant starch",
		"unit": "g"
	},
	{
		"id": 2028,
		"label": "trans-beta-Carotene",
		"unit": "µg"
	},
	{
		"id": 2029,
		"label": "trans-Lycopene",
		"unit": "µg"
	},
	{
		"id": 2068,
		"label": "Vitamin E",
		"unit": "mg"
	},
	{
		"id": 1188,
		"label": "5-methyl tetrahydrofolate (5-MTHF)",
		"unit": "µg"
	},
	{
		"id": 1118,
		"label": "Carotene, gamma",
		"unit": "µg"
	},
	{
		"id": 1340,
		"label": "Daidzein",
		"unit": "mg"
	},
	{
		"id": 2049,
		"label": "Daidzin",
		"unit": "mg"
	},
	{
		"id": 1341,
		"label": "Genistein",
		"unit": "mg"
	},
	{
		"id": 2050,
		"label": "Genistin",
		"unit": "mg"
	},
	{
		"id": 2051,
		"label": "Glycitin",
		"unit": "mg"
	},
	{
		"id": 1413,
		"label": "MUFA 18:1-11 c (18:1c n-7)",
		"unit": "g"
	},
	{
		"id": 1407,
		"label": "PUFA 20:4 n-3",
		"unit": "g"
	},
	{
		"id": 1076,
		"label": "Raffinose",
		"unit": "g"
	},
	{
		"id": 1024,
		"label": "Specific Gravity",
		"unit": "SP_GR"
	},
	{
		"id": 1077,
		"label": "Stachyose",
		"unit": "g"
	},
	{
		"id": 1086,
		"label": "Total sugar alcohols",
		"unit": "g"
	},
	{
		"id": 2063,
		"label": "Verbascose",
		"unit": "g"
	},
	{
		"id": 1158,
		"label": "Vitamin E",
		"unit": "MG_ATE"
	}
] as const;
